languageCode: en-us
title: Onboarding Template
copyright: Template Footer
pluralizelisttitles: false
markup:
  goldmark:
    renderer:
      Unsafe: true
params:
  appleScope: ""
  audience: ""
  logo: /media/images/logo.png
  scope: ""
sectionPagesMenu: ""
menu:
  Main:
  - identifier: Organization Overview
    name: Organization Overview
    url: /
    weight: 1
  - identifier: Solution Overview
    name: Solution Overview
    url: /solution-overview/
    weight: 2
  - identifier: Technology Stack
    name: Technology Stack
    url: /technology-stack/
    weight: 3
  - identifier: Tool Chain
    name: Tool Chain
    url: /tool-chain/
    weight: 4
  - identifier: Dev Environment Setup
    name: Dev Environment Setup
    url: /dev-environment-setup/
    weight: 5
  - identifier: Getting Started
    name: Getting Started
    url: /getting-started/
    weight: 6
  - identifier: Reference
    name: Reference
    url: /reference/
    weight: 7
  - identifier: Updates
    name: Updates
    url: /updates/
    weight: 8
outputFormats:
  MenuIndex:
    baseName: menu
    mediaType: application/json
  SearchMap:
    baseName: searchmap
    mediaType: application/json
outputs:
  home:
  - HTML
  - RSS
  - MenuIndex
  - SearchMap
module:
  imports:
  - path: github.com/spandigital/presidium-theme-website
    disabled: false
  - path: github.com/spandigital/presidium-theme-pdf
    disabled: true
enableInlineShortcodes: true
frontmatter:
  lastmod:
  - lastmod
  - :fileModTime
  - :default
